jwt:
  secretKey: ecf1222c-88fd-47f3-988f-bdd78bade1ad
  validityInMs: 3600000 # 1h

logging:
  level:
    com.ahmedmq: DEBUG

spring:
  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: sa
    password:

github:
  host: https://api.github.com
  version: 2022-11-28